<?php
if(!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED!==true)die();
IncludeModuleLangFile($_SERVER['DOCUMENT_ROOT'].'/bitrix/modules/intranet/public/.bottom.menu.php');

$aMenuLinks = Array(
	Array(
		GetMessage('BOTTOM_MENU_PRINT_VERSION'),
		'#print', 
		Array(),
		Array(),
		''
	),
	Array(
		GetMessage('BOTTOM_MENU_CONTACTS'),
		SITE_DIR.'about/company/contacts.php',
		Array(), 
		Array(), 
		'' 
	),
	Array(
		GetMessage('BOTTOM_MENU_SEARCH'),
		SITE_DIR.'search/',
		Array(), 
		Array(), 
		'' 
	),
	Array(
		GetMessage('BOTTOM_MENU_MAP'),
		SITE_DIR.'search/map.php',
		Array(), 
		Array(), 
		'' 
	),
	Array(
		GetMessage('BOTTOM_MENU_HELP'),
		SITE_DIR.'services/help/',
		Array(), 
		Array(), 
		'' 
	),
);